name: 'GitHub Contributions'
description:
  'Collects GitHub activity for a list of users and reports it to Slack'
author: 'Viget Labs'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'activity'
  color: 'green'

# Define your inputs here.
inputs:
  days:
    description: 'The duration of days to collect activity for'
    default: '7'
  github-token:
    description: 'Classic GitHub access token with `repo` scope'
    required: true
  slack-token:
    description: 'Slack bot access token'
    required: true
  slack-channel-id:
    description: 'Slack channel ID to post to'
    required: true
  users:
    description: 'Comma-separated list of GitHub usernames'
    required: true

outputs:
  json:
    description: 'JSON-encoded activity summary'
    value: ${{ steps.collect.outputs.json }}
  slackBlocks:
    description: 'JSON-encoded slack blocks'
    value: ${{ steps.collect.outputs.slackBlocks }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Collect GitHub activity
      uses: ./dist/index
      id: collect
      with:
        days: ${{ inputs.days }}
        token: ${{ inputs.token }}
        users: ${{ inputs.users }}

    - name: Send message to Slack API
      uses: archive/github-actions-slack@v2.8.0
      id: notify
      if: "${{ steps.collect.outputs.slackBlocks != '' }}"
      with:
        slack-bot-user-oauth-access-token: ${{ inputs.slack_token }}
        slack-channel: ${{ inputs.slack_channel_id }}
        slack-blocks: '${{ steps.collect.outputs.slackBlocks }}'
